# No supervisado datos
* Utilizar PCA, para observar los datos
* Utilizar K-means para agrupar los datos
* Utilizar PCA y Cluster para entender nuestros datos o generar etiquetas

In [1]:
! pip install numpy pandas plotly scipy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 32.9 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


In [109]:
import numpy as np
import os
import pandas as pd
from scipy import stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import tarfile
import zipfile
from sklearn.cluster import AgglomerativeClustering
from scipy.io import loadmat
from urllib.request import urlretrieve
from os.path import isfile, isdir
import plotly.figure_factory as ff
import plotly.express as px
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
%matplotlib inline

## PCA
* Cuales modelos son similares?

In [5]:
df = pd.read_csv("data/CARS.csv")
df["Invoice"] = df["Invoice"].replace('[\$,]', '', regex=True).astype(float)

In [115]:
df[["EngineSize","MPG_City"]].head(20).to_csv("~/Downloads/head.csv")

In [12]:
df.describe(include="all")

Make     Model   Type Origin DriveTrain     MSRP  Invoice  \
count      428       428    428    428        428      428      428   
unique      38       425      6      3          3      410      425   
top     Toyota  C240 4dr  Sedan   Asia      Front  $23,895  $68,306   
freq        28         2    262    158        226        2        2   
mean       NaN       NaN    NaN    NaN        NaN      NaN      NaN   
std        NaN       NaN    NaN    NaN        NaN      NaN      NaN   
min        NaN       NaN    NaN    NaN        NaN      NaN      NaN   
25%        NaN       NaN    NaN    NaN        NaN      NaN      NaN   
50%        NaN       NaN    NaN    NaN        NaN      NaN      NaN   
75%        NaN       NaN    NaN    NaN        NaN      NaN      NaN   
max        NaN       NaN    NaN    NaN        NaN      NaN      NaN   

        EngineSize   Cylinders  Horsepower    MPG_City  MPG_Highway  \
count   428.000000  426.000000  428.000000  428.000000   428.000000   
unique         NaN         NaN         NaN         NaN          NaN   
top            NaN         NaN         NaN         NaN          NaN   
freq           NaN         NaN         NaN         NaN          NaN   
mean      3.196729    5.807512  215.885514   20.060748    26.843458   
std       1.108595    1.558443   71.836032    5.238218     5.741201   
min       1.300000    3.000000   73.000000   10.000000    12.000000   
25%       2.375000    4.000000  165.000000   17.000000    24.000000   
50%       3.000000    6.000000  210.000000   19.000000    26.000000   
75%       3.900000    6.000000  255.000000   21.250000    29.000000   
max       8.300000   12.000000  500.000000   60.000000    66.000000   

             Weight   Wheelbase      Length  
count    428.000000  428.000000  428.000000  
unique          NaN         NaN         NaN  
top             NaN         NaN         NaN  
freq            NaN         NaN         NaN  
mean    3577.953271  108.154206  186.362150  
std      758.983215    8.311813   14.357991  
min     1850.000000   89.000000  143.000000  
25%     3104.000000  103.000000  178.000000  
50%     3474.500000  107.000000  187.000000  
75%     3977.750000  112.000000  194.000000  
max     7190.000000  144.000000  238.000000

In [119]:
df

Make                                    Model    Type  Origin  \
0            Acura                                      MDX     SUV    Asia   
1            Acura                           RSX Type S 2dr   Sedan    Asia   
2            Acura                                  TSX 4dr   Sedan    Asia   
3            Acura                                   TL 4dr   Sedan    Asia   
4            Acura                               3.5 RL 4dr   Sedan    Asia   
5            Acura                  3.5 RL w/Navigation 4dr   Sedan    Asia   
6            Acura                   NSX coupe 2dr manual S  Sports    Asia   
7             Audi                              A4 1.8T 4dr   Sedan  Europe   
8             Audi                   A41.8T convertible 2dr   Sedan  Europe   
9             Audi                               A4 3.0 4dr   Sedan  Europe   
10            Audi                A4 3.0 Quattro 4dr manual   Sedan  Europe   
11            Audi                  A4 3.0 Quattro 4dr auto   Sedan  Europe   
12            Audi                               A6 3.0 4dr   Sedan  Europe   
13            Audi                       A6 3.0 Quattro 4dr   Sedan  Europe   
14            Audi                   A4 3.0 convertible 2dr   Sedan  Europe   
15            Audi           A4 3.0 Quattro convertible 2dr   Sedan  Europe   
16            Audi                 A6 2.7 Turbo Quattro 4dr   Sedan  Europe   
17            Audi                       A6 4.2 Quattro 4dr   Sedan  Europe   
18            Audi                         A8 L Quattro 4dr   Sedan  Europe   
19            Audi                           S4 Quattro 4dr   Sedan  Europe   
20            Audi                                 RS 6 4dr  Sports  Europe   
21            Audi           TT 1.8 convertible 2dr (coupe)  Sports  Europe   
22            Audi         TT 1.8 Quattro 2dr (convertible)  Sports  Europe   
23            Audi           TT 3.2 coupe 2dr (convertible)  Sports  Europe   
24            Audi                     A6 3.0 Avant Quattro   Wagon  Europe   
25            Audi                         S4 Avant Quattro   Wagon  Europe   
26             BMW                                  X3 3.0i     SUV  Europe   
27             BMW                                  X5 4.4i     SUV  Europe   
28             BMW                                 325i 4dr   Sedan  Europe   
29             BMW                                325Ci 2dr   Sedan  Europe   
30             BMW                    325Ci convertible 2dr   Sedan  Europe   
31             BMW                                325xi 4dr   Sedan  Europe   
32             BMW                                 330i 4dr   Sedan  Europe   
33             BMW                                330Ci 2dr   Sedan  Europe   
34             BMW                                330xi 4dr   Sedan  Europe   
35             BMW                                 525i 4dr   Sedan  Europe   
36             BMW                    330Ci convertible 2dr   Sedan  Europe   
37             BMW                                 530i 4dr   Sedan  Europe   
38             BMW                                545iA 4dr   Sedan  Europe   
39             BMW                                 745i 4dr   Sedan  Europe   
40             BMW                                745Li 4dr   Sedan  Europe   
41             BMW                             M3 coupe 2dr  Sports  Europe   
42             BMW                       M3 convertible 2dr  Sports  Europe   
43             BMW                  Z4 convertible 2.5i 2dr  Sports  Europe   
44             BMW                  Z4 convertible 3.0i 2dr  Sports  Europe   
45             BMW                              325xi Sport   Wagon  Europe   
46           Buick                                  Rainier     SUV     USA   
47           Buick                            Rendezvous CX     SUV     USA   
48           Buick                       Century Custom 4dr   Sedan     USA   
49           Buick                       LeSabre Custom 4dr   Se

In [124]:
pca = PCA(n_components=3)
X = df[["EngineSize","Cylinders","Horsepower","MPG_City","MPG_Highway","Weight","Wheelbase","Length"]].fillna(0)
# center, remove mean
#X = X.sub(X.mean(axis=0), axis=1)
scaler = StandardScaler()
scaler.fit(X)
X_sc = scaler.transform(X)
pca.fit(X_sc)

PCA(n_components=3)

In [125]:
pca.explained_variance_ratio_

array([0.71064877, 0.13328633, 0.07708665])

In [122]:
pca.components_

array([[-0.38777255, -0.36326891, -0.33140171,  0.35867452,  0.35957626,
        -0.38389832, -0.32249629, -0.31387383],
       [ 0.08763927,  0.18034495,  0.39715417, -0.25114062, -0.24366903,
        -0.10688009, -0.57353016, -0.58245791]])

In [74]:
pca = PCA(n_components=2)
X = df[["EngineSize","Cylinders","Horsepower","MPG_City","MPG_Highway","Weight","Wheelbase","Length"]].fillna(0)
# center, remove mean
#X = X.sub(X.mean(axis=0), axis=1)
scaler = StandardScaler()
scaler.fit(X)
X_sc = scaler.transform(X)
pca.fit(X_sc)
X_hat = pca.transform(X_sc)
df_2d = pd.DataFrame(data=X_hat,columns=["comp1","comp2"])
df_2d["Model"] = df["Model"]
df_2d["Make"] = df["Make"]
fig = px.scatter(df_2d, x="comp1", y="comp2", 
                 color="Make", custom_data=['Make', 'Model'],
                 title="Autos 2D with PCA"
                )
fig.update_traces( hovertemplate='Comp1: %{x} <br>Comp2: %{y} <br>Brand: %{customdata[0]}-%{customdata[1]}')

In [75]:
# eigne vectors
pca.explained_variance_

array([5.69850446, 1.06878782])

In [76]:
# eigen vector
pca.components_

array([[-0.38777255, -0.36326891, -0.33140171,  0.35867452,  0.35957626,
        -0.38389832, -0.32249629, -0.31387383],
       [ 0.08763927,  0.18034495,  0.39715417, -0.25114062, -0.24366903,
        -0.10688009, -0.57353016, -0.58245791]])

#### More exmaples on
https://jdramirez.github.io/UCO_ML_AI/PCA.html

## K-Mean
Use k-means to find similar cars

In [77]:
kmeans = KMeans(n_clusters=4, random_state=0).fit(X_sc)

In [78]:
# centroides
kmeans.cluster_centers_

array([[-1.1175571 , -1.16286836, -1.05154231,  1.21302464,  1.1414147 ,
        -1.10217583, -0.83719832, -0.88653629],
       [-0.15186283, -0.08262071, -0.06282695, -0.15105604, -0.05455511,
        -0.09088182, -0.11567295, -0.03841553],
       [ 1.18079808,  0.89281252,  0.55671532, -0.8891844 , -1.06566823,
         1.51854331,  1.5150616 ,  1.33102836],
       [ 1.25706826,  1.4791274 ,  1.62931818, -0.7220299 , -0.69655741,
         0.54775946,  0.10414987,  0.16551601]])

In [79]:
kmeans.labels_

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 3, 3, 0,
       0, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 1, 3, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 3, 3, 3, 2, 2, 2, 2,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 3, 3, 2, 1, 2, 2,
       2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 0, 0, 1, 1,
       1, 1, 1, 2, 3, 1, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2,
       2, 1, 3, 3, 2, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 3, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 2, 3, 1, 3, 2,
       1, 1, 1, 1, 1, 3, 3, 3, 1, 2, 2, 1, 1, 3, 3, 2, 2, 2, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 2, 2, 3, 0, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1,
       3, 1, 3, 2, 2, 3, 3, 3, 0, 1, 1, 1, 3, 2, 1, 2, 2, 1, 2, 2, 2, 1,
       1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 1,

In [88]:
df_2d["labels"] = [str(i) for i in kmeans.labels_] 

In [89]:
df_2d_centroide = pd.DataFrame(data=pca.transform(kmeans.cluster_centers_), columns=["comp1","comp2"])
df_2d_centroide["is_centroide"] = "Y"
df_2d_centroide["labels"] = [str(i) for i in range(4)]
df_2d["is_centroide"] = "N"
df_2d_w_c = pd.concat((df_2d,df_2d_centroide), axis=0)

fig = px.scatter(df_2d_w_c, x="comp1", y="comp2", 
                 color="labels", custom_data=['Make', 'Model'],
                 symbol="is_centroide",
                 title="Autos 2D with PCA and K-means"
                )
fig.update_traces( hovertemplate='Comp1: %{x} <br>Comp2: %{y} <br>Brand: %{customdata[0]}-%{customdata[1]}')

## Dendograma
Cluster haciendo jerarquias

In [107]:
fig = ff.create_dendrogram(X_sc,  labels=(df_2d["Make"] +'-'+ df["Model"]).values)
fig.update_layout(width=5000, height=2000)
fig.show()

In [113]:
model = AgglomerativeClustering( n_clusters=4)
model = model.fit(X_sc)
model.labels_

array([2, 3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 3,
       3, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2,
       2, 1, 1, 3, 3, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 3, 0, 0,
       0, 2, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 0, 0, 2, 2, 0, 1, 1, 2, 3,
       3, 2, 3, 0, 0, 2, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 3, 2, 2, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 3, 3, 2, 0, 0, 0, 2, 3, 0, 0, 0, 1, 1, 2, 3, 3,
       1, 1, 1, 3, 3, 1, 3, 2, 2, 0, 0, 3, 0, 2, 1, 1, 1, 3, 3, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 3, 2, 2, 3, 1, 1, 3, 3, 3, 2, 2, 2, 1, 0, 0, 2, 0, 0,
       2, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 3, 3,
       3, 3, 2, 3, 3, 3, 3, 3, 0, 0, 0, 3, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2,
       0, 2, 0, 0, 0, 0, 0, 0, 3, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 2, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 0, 2,